#Use commands.yml to set aliases.
#Menu Config
menu-size: 54
#Multiples of 9 up to 54
menu-filler-location: 'bottom'
#glass panes you can't click | bottom, left, right, top, round, none
menu-filler-type: 'BLACK_STAINED_GLASS_PANE'
#Material https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
sell-item: 'EMERALD'
#Material https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
sell-item-glimmer: true
#enchanted effect | true, false
sell-item-location: 'middle'
#left, middle, right
sell-item-side: 'bottom'
#top, left, bottom, right | Only matters if filler is set to none or round.
#
confirm-item: 'EMERALD_BLOCK'
#Material https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
confirm-item-glimmer: true
#encahnted effect | true, false
close-after-sell: true
#closes menu after selling
use-essentials-price: false
#uses pricing from essentials
use-permission-bonuses-on-essentials: true
#uses permission based bonuses/multipliers on essentials pricing
drop-items-on-close: false
#Attempts to add items to inventory if false
prevent-custom-item-selling: false
#Makes price of anything with ItemMeta (Display Name, Enchants, Lore) 0.00. Bypassable via custom item pricing
log-transactions: false
#Logs transactions
#enables logging of transactions
round-places: true
#enables rounding of numbers
places-to-round: 2
#Amount of places for numbers to be rounded
sell-all-command-sell-enchanted: false
#Allows /sellall command to sell enchanted items.
